/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CommentV2 {
  'id' : string,
  'pseudonym' : string,
  'commenter' : Principal,
  'comment' : string,
  'timestamp' : Time,
  'postId' : string,
}
export interface DirectMessage {
  'id' : DirectMessageId,
  'to' : Principal,
  'isCrisisResource' : boolean,
  'content' : string,
  'from' : [] | [Principal],
  'read' : boolean,
  'timestamp' : Time,
}
export type DirectMessageId = string;
export type EmotionType = { 'confess' : null } |
  { 'happy' : null } |
  { 'broke' : null };
export type FlagReason = { 'Spam' : null } |
  { 'Offensive' : null } |
  { 'Harassment' : null } |
  { 'Other' : string };
export interface FlagV2 {
  'id' : string,
  'timestamp' : Time,
  'reporter' : Principal,
  'reason' : FlagReason,
  'postId' : string,
}
export interface InviteCode {
  'created' : Time,
  'code' : string,
  'used' : boolean,
}
export type MessageType = { 'resource' : null } |
  { 'admin' : null };
export interface Post {
  'id' : string,
  'emotionType' : EmotionType,
  'content' : string,
  'createdAt' : Time,
  'author' : Principal,
  'updatedAt' : Time,
  'flaggedForReview' : ReviewFlag,
  'visibility' : Visibility,
}
export interface RSVP {
  'name' : string,
  'inviteCode' : string,
  'timestamp' : Time,
  'attending' : boolean,
}
export type Region = { 'India' : null } |
  { 'Global' : null };
export type RegistrationError = { 'AnonymousNotAllowed' : null } |
  { 'CapacityReached' : null } |
  { 'InviteCodeUsed' : null } |
  { 'AlreadyRegistered' : null } |
  { 'InvalidInviteCode' : null };
export type Result = { 'ok' : Post } |
  { 'err' : string };
export type Result_1 = { 'ok' : User } |
  { 'err' : RegistrationError };
export type ReviewFlag = { 'none' : null } |
  { 'crisisRisk' : null };
export interface SeatInfo { 'maxSeats' : bigint, 'currentSeats' : bigint }
export type SubscriptionStatus = { 'active' : null } |
  { 'expired' : null } |
  { 'grace' : null };
export type Time = bigint;
export interface User {
  'id' : Principal,
  'region' : Region,
  'pseudonym' : string,
  'createdAt' : Time,
  'publicPostingCooldownUntil' : Time,
  'subscriptionStatus' : SubscriptionStatus,
  'suspended' : boolean,
  'hasAcknowledgedEntryMessage' : boolean,
  'hasAcknowledgedPublicPostMessage' : boolean,
}
export interface UserProfile {
  'region' : Region,
  'pseudonym' : string,
  'subscriptionStatus' : SubscriptionStatus,
  'suspended' : boolean,
  'hasAcknowledgedEntryMessage' : boolean,
  'hasAcknowledgedPublicPostMessage' : boolean,
}
export interface UserProfileUpdate { 'region' : Region, 'pseudonym' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Visibility = { 'publicView' : null } |
  { 'privateView' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acknowledgeEntryMessage' : ActorMethod<[], undefined>,
  'acknowledgePublicPostMessage' : ActorMethod<[], undefined>,
  /**
   * / *** COMMENTS STORE AND FLAG SYSTEM ***
   */
  'addComment' : ActorMethod<[string, string, string], string>,
  'applyPublicPostingCooldown' : ActorMethod<[Principal], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createPost' : ActorMethod<[EmotionType, string], Result>,
  'deleteComment' : ActorMethod<[string], undefined>,
  'flagPost' : ActorMethod<[string, FlagReason], string>,
  'generateInviteCode' : ActorMethod<[], string>,
  'getAllAdminUsers' : ActorMethod<[], Array<User>>,
  'getAllRSVPs' : ActorMethod<[], Array<RSVP>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getComments' : ActorMethod<[string], Array<CommentV2>>,
  'getDirectMessagesForUser' : ActorMethod<[Principal], Array<DirectMessage>>,
  'getFlags' : ActorMethod<[], Array<FlagV2>>,
  'getInviteCodes' : ActorMethod<[], Array<InviteCode>>,
  'getMyPosts' : ActorMethod<[], Array<Post>>,
  'getPublicPosts' : ActorMethod<[], Array<Post>>,
  'getSeatInfo' : ActorMethod<[], SeatInfo>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markDirectMessageAsRead' : ActorMethod<[DirectMessageId], undefined>,
  'permanentlyRemoveUser' : ActorMethod<[Principal], undefined>,
  'register' : ActorMethod<[string, Region, string], Result_1>,
  'removePost' : ActorMethod<[string], undefined>,
  'revokeInviteCode' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfileUpdate], undefined>,
  'sendAdminMessage' : ActorMethod<
    [Principal, MessageType, string],
    DirectMessageId
  >,
  'sendCrisisResourceMessage' : ActorMethod<
    [Principal, MessageType],
    DirectMessageId
  >,
  'submitRSVP' : ActorMethod<[string, boolean, string], undefined>,
  'suspendUser' : ActorMethod<[Principal], undefined>,
  'togglePostVisibility' : ActorMethod<[string], Result>,
  'unsuspendUser' : ActorMethod<[Principal], undefined>,
  'validateInviteCode' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];