/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const EmotionType = IDL.Variant({
  'confess' : IDL.Null,
  'happy' : IDL.Null,
  'broke' : IDL.Null,
});
export const Time = IDL.Int;
export const ReviewFlag = IDL.Variant({
  'none' : IDL.Null,
  'crisisRisk' : IDL.Null,
});
export const Visibility = IDL.Variant({
  'publicView' : IDL.Null,
  'privateView' : IDL.Null,
});
export const Post = IDL.Record({
  'id' : IDL.Text,
  'emotionType' : EmotionType,
  'content' : IDL.Text,
  'createdAt' : Time,
  'author' : IDL.Principal,
  'updatedAt' : Time,
  'flaggedForReview' : ReviewFlag,
  'visibility' : Visibility,
});
export const Result = IDL.Variant({ 'ok' : Post, 'err' : IDL.Text });
export const FlagReason = IDL.Variant({
  'Spam' : IDL.Null,
  'Offensive' : IDL.Null,
  'Harassment' : IDL.Null,
  'Other' : IDL.Text,
});
export const Region = IDL.Variant({ 'India' : IDL.Null, 'Global' : IDL.Null });
export const SubscriptionStatus = IDL.Variant({
  'active' : IDL.Null,
  'expired' : IDL.Null,
  'grace' : IDL.Null,
});
export const User = IDL.Record({
  'id' : IDL.Principal,
  'region' : Region,
  'pseudonym' : IDL.Text,
  'createdAt' : Time,
  'publicPostingCooldownUntil' : Time,
  'subscriptionStatus' : SubscriptionStatus,
  'suspended' : IDL.Bool,
  'hasAcknowledgedEntryMessage' : IDL.Bool,
  'hasAcknowledgedPublicPostMessage' : IDL.Bool,
});
export const RSVP = IDL.Record({
  'name' : IDL.Text,
  'inviteCode' : IDL.Text,
  'timestamp' : Time,
  'attending' : IDL.Bool,
});
export const UserProfile = IDL.Record({
  'region' : Region,
  'pseudonym' : IDL.Text,
  'subscriptionStatus' : SubscriptionStatus,
  'suspended' : IDL.Bool,
  'hasAcknowledgedEntryMessage' : IDL.Bool,
  'hasAcknowledgedPublicPostMessage' : IDL.Bool,
});
export const CommentV2 = IDL.Record({
  'id' : IDL.Text,
  'pseudonym' : IDL.Text,
  'commenter' : IDL.Principal,
  'comment' : IDL.Text,
  'timestamp' : Time,
  'postId' : IDL.Text,
});
export const DirectMessageId = IDL.Text;
export const DirectMessage = IDL.Record({
  'id' : DirectMessageId,
  'to' : IDL.Principal,
  'isCrisisResource' : IDL.Bool,
  'content' : IDL.Text,
  'from' : IDL.Opt(IDL.Principal),
  'read' : IDL.Bool,
  'timestamp' : Time,
});
export const FlagV2 = IDL.Record({
  'id' : IDL.Text,
  'timestamp' : Time,
  'reporter' : IDL.Principal,
  'reason' : FlagReason,
  'postId' : IDL.Text,
});
export const InviteCode = IDL.Record({
  'created' : Time,
  'code' : IDL.Text,
  'used' : IDL.Bool,
});
export const SeatInfo = IDL.Record({
  'maxSeats' : IDL.Nat,
  'currentSeats' : IDL.Nat,
});
export const RegistrationError = IDL.Variant({
  'AnonymousNotAllowed' : IDL.Null,
  'CapacityReached' : IDL.Null,
  'InviteCodeUsed' : IDL.Null,
  'AlreadyRegistered' : IDL.Null,
  'InvalidInviteCode' : IDL.Null,
});
export const Result_1 = IDL.Variant({ 'ok' : User, 'err' : RegistrationError });
export const UserProfileUpdate = IDL.Record({
  'region' : Region,
  'pseudonym' : IDL.Text,
});
export const MessageType = IDL.Variant({
  'resource' : IDL.Null,
  'admin' : IDL.Null,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acknowledgeEntryMessage' : IDL.Func([], [], []),
  'acknowledgePublicPostMessage' : IDL.Func([], [], []),
  'addComment' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
  'applyPublicPostingCooldown' : IDL.Func([IDL.Principal], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createPost' : IDL.Func([EmotionType, IDL.Text], [Result], []),
  'deleteComment' : IDL.Func([IDL.Text], [], []),
  'flagPost' : IDL.Func([IDL.Text, FlagReason], [IDL.Text], []),
  'generateInviteCode' : IDL.Func([], [IDL.Text], []),
  'getAllAdminUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'getAllRSVPs' : IDL.Func([], [IDL.Vec(RSVP)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getComments' : IDL.Func([IDL.Text], [IDL.Vec(CommentV2)], ['query']),
  'getDirectMessagesForUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(DirectMessage)],
      ['query'],
    ),
  'getFlags' : IDL.Func([], [IDL.Vec(FlagV2)], ['query']),
  'getInviteCodes' : IDL.Func([], [IDL.Vec(InviteCode)], ['query']),
  'getMyPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getPublicPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getSeatInfo' : IDL.Func([], [SeatInfo], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markDirectMessageAsRead' : IDL.Func([DirectMessageId], [], []),
  'permanentlyRemoveUser' : IDL.Func([IDL.Principal], [], []),
  'register' : IDL.Func([IDL.Text, Region, IDL.Text], [Result_1], []),
  'removePost' : IDL.Func([IDL.Text], [], []),
  'revokeInviteCode' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfileUpdate], [], []),
  'sendAdminMessage' : IDL.Func(
      [IDL.Principal, MessageType, IDL.Text],
      [DirectMessageId],
      [],
    ),
  'sendCrisisResourceMessage' : IDL.Func(
      [IDL.Principal, MessageType],
      [DirectMessageId],
      [],
    ),
  'submitRSVP' : IDL.Func([IDL.Text, IDL.Bool, IDL.Text], [], []),
  'suspendUser' : IDL.Func([IDL.Principal], [], []),
  'togglePostVisibility' : IDL.Func([IDL.Text], [Result], []),
  'unsuspendUser' : IDL.Func([IDL.Principal], [], []),
  'validateInviteCode' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const EmotionType = IDL.Variant({
    'confess' : IDL.Null,
    'happy' : IDL.Null,
    'broke' : IDL.Null,
  });
  const Time = IDL.Int;
  const ReviewFlag = IDL.Variant({
    'none' : IDL.Null,
    'crisisRisk' : IDL.Null,
  });
  const Visibility = IDL.Variant({
    'publicView' : IDL.Null,
    'privateView' : IDL.Null,
  });
  const Post = IDL.Record({
    'id' : IDL.Text,
    'emotionType' : EmotionType,
    'content' : IDL.Text,
    'createdAt' : Time,
    'author' : IDL.Principal,
    'updatedAt' : Time,
    'flaggedForReview' : ReviewFlag,
    'visibility' : Visibility,
  });
  const Result = IDL.Variant({ 'ok' : Post, 'err' : IDL.Text });
  const FlagReason = IDL.Variant({
    'Spam' : IDL.Null,
    'Offensive' : IDL.Null,
    'Harassment' : IDL.Null,
    'Other' : IDL.Text,
  });
  const Region = IDL.Variant({ 'India' : IDL.Null, 'Global' : IDL.Null });
  const SubscriptionStatus = IDL.Variant({
    'active' : IDL.Null,
    'expired' : IDL.Null,
    'grace' : IDL.Null,
  });
  const User = IDL.Record({
    'id' : IDL.Principal,
    'region' : Region,
    'pseudonym' : IDL.Text,
    'createdAt' : Time,
    'publicPostingCooldownUntil' : Time,
    'subscriptionStatus' : SubscriptionStatus,
    'suspended' : IDL.Bool,
    'hasAcknowledgedEntryMessage' : IDL.Bool,
    'hasAcknowledgedPublicPostMessage' : IDL.Bool,
  });
  const RSVP = IDL.Record({
    'name' : IDL.Text,
    'inviteCode' : IDL.Text,
    'timestamp' : Time,
    'attending' : IDL.Bool,
  });
  const UserProfile = IDL.Record({
    'region' : Region,
    'pseudonym' : IDL.Text,
    'subscriptionStatus' : SubscriptionStatus,
    'suspended' : IDL.Bool,
    'hasAcknowledgedEntryMessage' : IDL.Bool,
    'hasAcknowledgedPublicPostMessage' : IDL.Bool,
  });
  const CommentV2 = IDL.Record({
    'id' : IDL.Text,
    'pseudonym' : IDL.Text,
    'commenter' : IDL.Principal,
    'comment' : IDL.Text,
    'timestamp' : Time,
    'postId' : IDL.Text,
  });
  const DirectMessageId = IDL.Text;
  const DirectMessage = IDL.Record({
    'id' : DirectMessageId,
    'to' : IDL.Principal,
    'isCrisisResource' : IDL.Bool,
    'content' : IDL.Text,
    'from' : IDL.Opt(IDL.Principal),
    'read' : IDL.Bool,
    'timestamp' : Time,
  });
  const FlagV2 = IDL.Record({
    'id' : IDL.Text,
    'timestamp' : Time,
    'reporter' : IDL.Principal,
    'reason' : FlagReason,
    'postId' : IDL.Text,
  });
  const InviteCode = IDL.Record({
    'created' : Time,
    'code' : IDL.Text,
    'used' : IDL.Bool,
  });
  const SeatInfo = IDL.Record({
    'maxSeats' : IDL.Nat,
    'currentSeats' : IDL.Nat,
  });
  const RegistrationError = IDL.Variant({
    'AnonymousNotAllowed' : IDL.Null,
    'CapacityReached' : IDL.Null,
    'InviteCodeUsed' : IDL.Null,
    'AlreadyRegistered' : IDL.Null,
    'InvalidInviteCode' : IDL.Null,
  });
  const Result_1 = IDL.Variant({ 'ok' : User, 'err' : RegistrationError });
  const UserProfileUpdate = IDL.Record({
    'region' : Region,
    'pseudonym' : IDL.Text,
  });
  const MessageType = IDL.Variant({
    'resource' : IDL.Null,
    'admin' : IDL.Null,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acknowledgeEntryMessage' : IDL.Func([], [], []),
    'acknowledgePublicPostMessage' : IDL.Func([], [], []),
    'addComment' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
    'applyPublicPostingCooldown' : IDL.Func([IDL.Principal], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createPost' : IDL.Func([EmotionType, IDL.Text], [Result], []),
    'deleteComment' : IDL.Func([IDL.Text], [], []),
    'flagPost' : IDL.Func([IDL.Text, FlagReason], [IDL.Text], []),
    'generateInviteCode' : IDL.Func([], [IDL.Text], []),
    'getAllAdminUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'getAllRSVPs' : IDL.Func([], [IDL.Vec(RSVP)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getComments' : IDL.Func([IDL.Text], [IDL.Vec(CommentV2)], ['query']),
    'getDirectMessagesForUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(DirectMessage)],
        ['query'],
      ),
    'getFlags' : IDL.Func([], [IDL.Vec(FlagV2)], ['query']),
    'getInviteCodes' : IDL.Func([], [IDL.Vec(InviteCode)], ['query']),
    'getMyPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getPublicPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getSeatInfo' : IDL.Func([], [SeatInfo], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markDirectMessageAsRead' : IDL.Func([DirectMessageId], [], []),
    'permanentlyRemoveUser' : IDL.Func([IDL.Principal], [], []),
    'register' : IDL.Func([IDL.Text, Region, IDL.Text], [Result_1], []),
    'removePost' : IDL.Func([IDL.Text], [], []),
    'revokeInviteCode' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfileUpdate], [], []),
    'sendAdminMessage' : IDL.Func(
        [IDL.Principal, MessageType, IDL.Text],
        [DirectMessageId],
        [],
      ),
    'sendCrisisResourceMessage' : IDL.Func(
        [IDL.Principal, MessageType],
        [DirectMessageId],
        [],
      ),
    'submitRSVP' : IDL.Func([IDL.Text, IDL.Bool, IDL.Text], [], []),
    'suspendUser' : IDL.Func([IDL.Principal], [], []),
    'togglePostVisibility' : IDL.Func([IDL.Text], [Result], []),
    'unsuspendUser' : IDL.Func([IDL.Principal], [], []),
    'validateInviteCode' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };