/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ReactionType = IDL.Variant({
  'support' : IDL.Null,
  'care' : IDL.Null,
  'strength' : IDL.Null,
});
export const EmotionType = IDL.Variant({
  'confess' : IDL.Null,
  'happy' : IDL.Null,
  'broke' : IDL.Null,
});
export const Time = IDL.Int;
export const Post = IDL.Record({
  'id' : IDL.Text,
  'emotionType' : EmotionType,
  'content' : IDL.Text,
  'reactionCount' : IDL.Nat,
  'userId' : IDL.Principal,
  'createdAt' : Time,
  'isPrivate' : IDL.Bool,
  'editable' : IDL.Bool,
});
export const Region = IDL.Variant({ 'India' : IDL.Null, 'Global' : IDL.Null });
export const SubscriptionStatus = IDL.Variant({
  'active' : IDL.Null,
  'expired' : IDL.Null,
  'grace' : IDL.Null,
});
export const User = IDL.Record({
  'id' : IDL.Principal,
  'region' : Region,
  'pseudonym' : IDL.Text,
  'createdAt' : Time,
  'subscriptionStatus' : SubscriptionStatus,
  'subscriptionStartDate' : Time,
  'inviteCode' : IDL.Text,
  'suspended' : IDL.Bool,
});
export const Result = IDL.Variant({ 'ok' : User, 'err' : IDL.Text });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const RSVP = IDL.Record({
  'name' : IDL.Text,
  'inviteCode' : IDL.Text,
  'timestamp' : Time,
  'attending' : IDL.Bool,
});
export const UserProfile = IDL.Record({
  'region' : Region,
  'pseudonym' : IDL.Text,
});
export const InviteCode = IDL.Record({
  'created' : Time,
  'code' : IDL.Text,
  'used' : IDL.Bool,
});
export const Reaction = IDL.Record({
  'id' : IDL.Text,
  'userId' : IDL.Principal,
  'createdAt' : Time,
  'reactionType' : ReactionType,
  'postId' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addInviteCode' : IDL.Func([IDL.Text], [], []),
  'addReaction' : IDL.Func([IDL.Text, ReactionType], [IDL.Text], []),
  'adminDeletePost' : IDL.Func([IDL.Text], [], []),
  'adminGetAllPublicPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'adminGetAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'adminGetUserPosts' : IDL.Func([IDL.Principal], [IDL.Vec(Post)], ['query']),
  'adminRegister' : IDL.Func([IDL.Text, Region], [Result], []),
  'adminSuspendUser' : IDL.Func([IDL.Principal], [], []),
  'adminUnsuspendUser' : IDL.Func([IDL.Principal], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createPost' : IDL.Func([EmotionType, IDL.Text], [IDL.Text], []),
  'deletePost' : IDL.Func([IDL.Text], [], []),
  'editPost' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'generateInviteCode' : IDL.Func([], [IDL.Text], []),
  'getAllRSVPs' : IDL.Func([], [IDL.Vec(RSVP)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getInviteCodes' : IDL.Func([], [IDL.Vec(InviteCode)], ['query']),
  'getMyPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(User)], ['query']),
  'getMyReaction' : IDL.Func([IDL.Text], [IDL.Opt(ReactionType)], ['query']),
  'getMySubscriptionStatus' : IDL.Func([], [SubscriptionStatus], ['query']),
  'getPublicPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getSubscriptionStatus' : IDL.Func(
      [IDL.Principal],
      [SubscriptionStatus],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserReactionOnPost' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(Reaction)],
      ['query'],
    ),
  'initializeAdmin' : IDL.Func([], [], []),
  'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'register' : IDL.Func([IDL.Text, Region], [Result], []),
  'revokeInviteCode' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setPostPrivacy' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'setSubscriptionStatus' : IDL.Func(
      [IDL.Principal, SubscriptionStatus],
      [],
      [],
    ),
  'submitRSVP' : IDL.Func([IDL.Text, IDL.Bool, IDL.Text], [], []),
  'validateInviteCode' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ReactionType = IDL.Variant({
    'support' : IDL.Null,
    'care' : IDL.Null,
    'strength' : IDL.Null,
  });
  const EmotionType = IDL.Variant({
    'confess' : IDL.Null,
    'happy' : IDL.Null,
    'broke' : IDL.Null,
  });
  const Time = IDL.Int;
  const Post = IDL.Record({
    'id' : IDL.Text,
    'emotionType' : EmotionType,
    'content' : IDL.Text,
    'reactionCount' : IDL.Nat,
    'userId' : IDL.Principal,
    'createdAt' : Time,
    'isPrivate' : IDL.Bool,
    'editable' : IDL.Bool,
  });
  const Region = IDL.Variant({ 'India' : IDL.Null, 'Global' : IDL.Null });
  const SubscriptionStatus = IDL.Variant({
    'active' : IDL.Null,
    'expired' : IDL.Null,
    'grace' : IDL.Null,
  });
  const User = IDL.Record({
    'id' : IDL.Principal,
    'region' : Region,
    'pseudonym' : IDL.Text,
    'createdAt' : Time,
    'subscriptionStatus' : SubscriptionStatus,
    'subscriptionStartDate' : Time,
    'inviteCode' : IDL.Text,
    'suspended' : IDL.Bool,
  });
  const Result = IDL.Variant({ 'ok' : User, 'err' : IDL.Text });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const RSVP = IDL.Record({
    'name' : IDL.Text,
    'inviteCode' : IDL.Text,
    'timestamp' : Time,
    'attending' : IDL.Bool,
  });
  const UserProfile = IDL.Record({ 'region' : Region, 'pseudonym' : IDL.Text });
  const InviteCode = IDL.Record({
    'created' : Time,
    'code' : IDL.Text,
    'used' : IDL.Bool,
  });
  const Reaction = IDL.Record({
    'id' : IDL.Text,
    'userId' : IDL.Principal,
    'createdAt' : Time,
    'reactionType' : ReactionType,
    'postId' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addInviteCode' : IDL.Func([IDL.Text], [], []),
    'addReaction' : IDL.Func([IDL.Text, ReactionType], [IDL.Text], []),
    'adminDeletePost' : IDL.Func([IDL.Text], [], []),
    'adminGetAllPublicPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'adminGetAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'adminGetUserPosts' : IDL.Func([IDL.Principal], [IDL.Vec(Post)], ['query']),
    'adminRegister' : IDL.Func([IDL.Text, Region], [Result], []),
    'adminSuspendUser' : IDL.Func([IDL.Principal], [], []),
    'adminUnsuspendUser' : IDL.Func([IDL.Principal], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createPost' : IDL.Func([EmotionType, IDL.Text], [IDL.Text], []),
    'deletePost' : IDL.Func([IDL.Text], [], []),
    'editPost' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'generateInviteCode' : IDL.Func([], [IDL.Text], []),
    'getAllRSVPs' : IDL.Func([], [IDL.Vec(RSVP)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getInviteCodes' : IDL.Func([], [IDL.Vec(InviteCode)], ['query']),
    'getMyPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(User)], ['query']),
    'getMyReaction' : IDL.Func([IDL.Text], [IDL.Opt(ReactionType)], ['query']),
    'getMySubscriptionStatus' : IDL.Func([], [SubscriptionStatus], ['query']),
    'getPublicPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getSubscriptionStatus' : IDL.Func(
        [IDL.Principal],
        [SubscriptionStatus],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserReactionOnPost' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(Reaction)],
        ['query'],
      ),
    'initializeAdmin' : IDL.Func([], [], []),
    'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'register' : IDL.Func([IDL.Text, Region], [Result], []),
    'revokeInviteCode' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setPostPrivacy' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'setSubscriptionStatus' : IDL.Func(
        [IDL.Principal, SubscriptionStatus],
        [],
        [],
      ),
    'submitRSVP' : IDL.Func([IDL.Text, IDL.Bool, IDL.Text], [], []),
    'validateInviteCode' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };