/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Comment {
  'id' : string,
  'content' : string,
  'createdAt' : Time,
  'author' : Principal,
  'postId' : string,
}
export type EmotionType = { 'confess' : null } |
  { 'happy' : null } |
  { 'broke' : null };
export interface Flag {
  'id' : string,
  'createdAt' : Time,
  'reporter' : Principal,
  'reason' : string,
  'postId' : string,
}
export interface InviteCode {
  'created' : Time,
  'code' : string,
  'used' : boolean,
}
export interface Post {
  'id' : string,
  'emotionType' : EmotionType,
  'content' : string,
  'createdAt' : Time,
  'author' : Principal,
  'isPrivate' : boolean,
}
export interface RSVP {
  'name' : string,
  'inviteCode' : string,
  'timestamp' : Time,
  'attending' : boolean,
}
export interface Reaction {
  'id' : string,
  'createdAt' : Time,
  'author' : Principal,
  'reactionType' : ReactionType,
  'postId' : string,
}
export type ReactionType = { 'support' : null } |
  { 'care' : null } |
  { 'strength' : null };
export type Region = { 'India' : null } |
  { 'Global' : null };
export type Result = { 'ok' : User } |
  { 'err' : string };
export type Result_1 = { 'ok' : string } |
  { 'err' : string };
export type SubscriptionStatus = { 'active' : null } |
  { 'expired' : null } |
  { 'grace' : null };
export type Time = bigint;
export interface User {
  'id' : Principal,
  'region' : Region,
  'pseudonym' : string,
  'createdAt' : Time,
  'subscriptionStatus' : SubscriptionStatus,
  'suspended' : boolean,
}
export interface UserProfile {
  'region' : Region,
  'pseudonym' : string,
  'subscriptionStatus' : SubscriptionStatus,
  'suspended' : boolean,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addComment' : ActorMethod<[string, string], string>,
  'addReaction' : ActorMethod<[string, ReactionType], string>,
  'adminClearESPFlag' : ActorMethod<[Principal], undefined>,
  'adminDeletePost' : ActorMethod<[string], undefined>,
  'adminGetAllPosts' : ActorMethod<[], Array<Post>>,
  'adminGetAllUsers' : ActorMethod<[], Array<User>>,
  'adminGetESPFlaggedUsers' : ActorMethod<[], Array<Principal>>,
  'adminGetFlaggedPosts' : ActorMethod<[], Array<Flag>>,
  'adminGetSeatCount' : ActorMethod<[], bigint>,
  'adminGetUserPosts' : ActorMethod<[Principal], Array<Post>>,
  'adminSetSubscriptionStatus' : ActorMethod<
    [Principal, SubscriptionStatus],
    undefined
  >,
  'adminSuspendUser' : ActorMethod<[Principal], undefined>,
  'adminUnsuspendUser' : ActorMethod<[Principal], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkLoginStatus' : ActorMethod<
    [],
    { 'existingUser' : null } |
      { 'anonymous' : null } |
      { 'newUser' : null }
  >,
  'createPost' : ActorMethod<[EmotionType, string, boolean], Result_1>,
  'flagPost' : ActorMethod<[string, string], string>,
  'generateInviteCode' : ActorMethod<[], string>,
  'getAllRSVPs' : ActorMethod<[], Array<RSVP>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCommentsForPost' : ActorMethod<[string], Array<Comment>>,
  'getESPStatus' : ActorMethod<[], boolean>,
  'getInviteCodes' : ActorMethod<[], Array<InviteCode>>,
  'getMyPosts' : ActorMethod<[], Array<Post>>,
  'getPublicPosts' : ActorMethod<[], Array<Post>>,
  'getReactionsForPost' : ActorMethod<[string], Array<Reaction>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'register' : ActorMethod<[string, Region, string], Result>,
  'revokeInviteCode' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitRSVP' : ActorMethod<[string, boolean, string], undefined>,
  'validateInviteCode' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];