/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ReactionType = IDL.Variant({
  'support' : IDL.Null,
  'care' : IDL.Null,
  'strength' : IDL.Null,
});
export const EmotionType = IDL.Variant({
  'confess' : IDL.Null,
  'happy' : IDL.Null,
  'broke' : IDL.Null,
});
export const Time = IDL.Int;
export const Visibility = IDL.Variant({
  'publicView' : IDL.Null,
  'privateView' : IDL.Null,
});
export const Post = IDL.Record({
  'id' : IDL.Text,
  'emotionType' : EmotionType,
  'content' : IDL.Text,
  'createdAt' : Time,
  'author' : IDL.Principal,
  'updatedAt' : Time,
  'visibility' : Visibility,
});
export const Region = IDL.Variant({ 'India' : IDL.Null, 'Global' : IDL.Null });
export const SubscriptionStatus = IDL.Variant({
  'active' : IDL.Null,
  'expired' : IDL.Null,
  'grace' : IDL.Null,
});
export const User = IDL.Record({
  'id' : IDL.Principal,
  'region' : Region,
  'pseudonym' : IDL.Text,
  'createdAt' : Time,
  'subscriptionStatus' : SubscriptionStatus,
  'suspended' : IDL.Bool,
  'hasAcknowledgedEntryMessage' : IDL.Bool,
  'hasAcknowledgedPublicPostMessage' : IDL.Bool,
});
export const Flag = IDL.Record({
  'id' : IDL.Text,
  'createdAt' : Time,
  'reporter' : IDL.Principal,
  'reason' : IDL.Text,
  'postId' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Result = IDL.Variant({ 'ok' : Post, 'err' : IDL.Text });
export const RSVP = IDL.Record({
  'name' : IDL.Text,
  'inviteCode' : IDL.Text,
  'timestamp' : Time,
  'attending' : IDL.Bool,
});
export const UserProfile = IDL.Record({
  'region' : Region,
  'pseudonym' : IDL.Text,
  'subscriptionStatus' : SubscriptionStatus,
  'suspended' : IDL.Bool,
  'hasAcknowledgedEntryMessage' : IDL.Bool,
  'hasAcknowledgedPublicPostMessage' : IDL.Bool,
});
export const Comment = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'createdAt' : Time,
  'author' : IDL.Principal,
  'postId' : IDL.Text,
});
export const InviteCode = IDL.Record({
  'created' : Time,
  'code' : IDL.Text,
  'used' : IDL.Bool,
});
export const Reaction = IDL.Record({
  'id' : IDL.Text,
  'createdAt' : Time,
  'author' : IDL.Principal,
  'reactionType' : ReactionType,
  'postId' : IDL.Text,
});
export const SeatInfo = IDL.Record({
  'maxSeats' : IDL.Nat,
  'currentSeats' : IDL.Nat,
});
export const TextReaction = IDL.Record({
  'id' : IDL.Text,
  'userId' : IDL.Principal,
  'createdAt' : Time,
  'reactionText' : IDL.Text,
  'postId' : IDL.Text,
});
export const RegistrationError = IDL.Variant({
  'AnonymousNotAllowed' : IDL.Null,
  'CapacityReached' : IDL.Null,
  'InviteCodeUsed' : IDL.Null,
  'AlreadyRegistered' : IDL.Null,
  'InvalidInviteCode' : IDL.Null,
});
export const Result_1 = IDL.Variant({ 'ok' : User, 'err' : RegistrationError });
export const UserProfileUpdate = IDL.Record({
  'region' : Region,
  'pseudonym' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acknowledgeEntryMessage' : IDL.Func([], [], []),
  'acknowledgePublicPostMessage' : IDL.Func([], [], []),
  'addComment' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'addReaction' : IDL.Func([IDL.Text, ReactionType], [IDL.Text], []),
  'addTextReaction' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'adminClearESPFlag' : IDL.Func([IDL.Principal], [], []),
  'adminDeletePost' : IDL.Func([IDL.Text], [], []),
  'adminGetAllPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'adminGetAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'adminGetESPFlaggedUsers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'adminGetFlaggedPosts' : IDL.Func([], [IDL.Vec(Flag)], ['query']),
  'adminGetUserPosts' : IDL.Func([IDL.Principal], [IDL.Vec(Post)], ['query']),
  'adminSetSubscriptionStatus' : IDL.Func(
      [IDL.Principal, SubscriptionStatus],
      [],
      [],
    ),
  'adminSuspendUser' : IDL.Func([IDL.Principal], [], []),
  'adminUnsuspendUser' : IDL.Func([IDL.Principal], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkLoginStatus' : IDL.Func(
      [],
      [
        IDL.Variant({
          'existingUser' : IDL.Null,
          'anonymous' : IDL.Null,
          'newUser' : IDL.Null,
        }),
      ],
      ['query'],
    ),
  'createPost' : IDL.Func(
      [EmotionType, IDL.Text, IDL.Opt(Visibility)],
      [Result],
      [],
    ),
  'flagPost' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'generateInviteCode' : IDL.Func([], [IDL.Text], []),
  'getAllRSVPs' : IDL.Func([], [IDL.Vec(RSVP)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCommentsForPost' : IDL.Func([IDL.Text], [IDL.Vec(Comment)], ['query']),
  'getESPStatus' : IDL.Func([], [IDL.Bool], ['query']),
  'getInviteCodes' : IDL.Func([], [IDL.Vec(InviteCode)], ['query']),
  'getMyPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getPublicPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getReactionsForPost' : IDL.Func([IDL.Text], [IDL.Vec(Reaction)], ['query']),
  'getSeatInfo' : IDL.Func([], [SeatInfo], ['query']),
  'getTextReactionsForPost' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(TextReaction)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'register' : IDL.Func([IDL.Text, Region, IDL.Text], [Result_1], []),
  'revokeInviteCode' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfileUpdate], [], []),
  'submitRSVP' : IDL.Func([IDL.Text, IDL.Bool, IDL.Text], [], []),
  'togglePostVisibility' : IDL.Func([IDL.Text], [Result], []),
  'validateInviteCode' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ReactionType = IDL.Variant({
    'support' : IDL.Null,
    'care' : IDL.Null,
    'strength' : IDL.Null,
  });
  const EmotionType = IDL.Variant({
    'confess' : IDL.Null,
    'happy' : IDL.Null,
    'broke' : IDL.Null,
  });
  const Time = IDL.Int;
  const Visibility = IDL.Variant({
    'publicView' : IDL.Null,
    'privateView' : IDL.Null,
  });
  const Post = IDL.Record({
    'id' : IDL.Text,
    'emotionType' : EmotionType,
    'content' : IDL.Text,
    'createdAt' : Time,
    'author' : IDL.Principal,
    'updatedAt' : Time,
    'visibility' : Visibility,
  });
  const Region = IDL.Variant({ 'India' : IDL.Null, 'Global' : IDL.Null });
  const SubscriptionStatus = IDL.Variant({
    'active' : IDL.Null,
    'expired' : IDL.Null,
    'grace' : IDL.Null,
  });
  const User = IDL.Record({
    'id' : IDL.Principal,
    'region' : Region,
    'pseudonym' : IDL.Text,
    'createdAt' : Time,
    'subscriptionStatus' : SubscriptionStatus,
    'suspended' : IDL.Bool,
    'hasAcknowledgedEntryMessage' : IDL.Bool,
    'hasAcknowledgedPublicPostMessage' : IDL.Bool,
  });
  const Flag = IDL.Record({
    'id' : IDL.Text,
    'createdAt' : Time,
    'reporter' : IDL.Principal,
    'reason' : IDL.Text,
    'postId' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Result = IDL.Variant({ 'ok' : Post, 'err' : IDL.Text });
  const RSVP = IDL.Record({
    'name' : IDL.Text,
    'inviteCode' : IDL.Text,
    'timestamp' : Time,
    'attending' : IDL.Bool,
  });
  const UserProfile = IDL.Record({
    'region' : Region,
    'pseudonym' : IDL.Text,
    'subscriptionStatus' : SubscriptionStatus,
    'suspended' : IDL.Bool,
    'hasAcknowledgedEntryMessage' : IDL.Bool,
    'hasAcknowledgedPublicPostMessage' : IDL.Bool,
  });
  const Comment = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'createdAt' : Time,
    'author' : IDL.Principal,
    'postId' : IDL.Text,
  });
  const InviteCode = IDL.Record({
    'created' : Time,
    'code' : IDL.Text,
    'used' : IDL.Bool,
  });
  const Reaction = IDL.Record({
    'id' : IDL.Text,
    'createdAt' : Time,
    'author' : IDL.Principal,
    'reactionType' : ReactionType,
    'postId' : IDL.Text,
  });
  const SeatInfo = IDL.Record({
    'maxSeats' : IDL.Nat,
    'currentSeats' : IDL.Nat,
  });
  const TextReaction = IDL.Record({
    'id' : IDL.Text,
    'userId' : IDL.Principal,
    'createdAt' : Time,
    'reactionText' : IDL.Text,
    'postId' : IDL.Text,
  });
  const RegistrationError = IDL.Variant({
    'AnonymousNotAllowed' : IDL.Null,
    'CapacityReached' : IDL.Null,
    'InviteCodeUsed' : IDL.Null,
    'AlreadyRegistered' : IDL.Null,
    'InvalidInviteCode' : IDL.Null,
  });
  const Result_1 = IDL.Variant({ 'ok' : User, 'err' : RegistrationError });
  const UserProfileUpdate = IDL.Record({
    'region' : Region,
    'pseudonym' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acknowledgeEntryMessage' : IDL.Func([], [], []),
    'acknowledgePublicPostMessage' : IDL.Func([], [], []),
    'addComment' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'addReaction' : IDL.Func([IDL.Text, ReactionType], [IDL.Text], []),
    'addTextReaction' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'adminClearESPFlag' : IDL.Func([IDL.Principal], [], []),
    'adminDeletePost' : IDL.Func([IDL.Text], [], []),
    'adminGetAllPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'adminGetAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'adminGetESPFlaggedUsers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'adminGetFlaggedPosts' : IDL.Func([], [IDL.Vec(Flag)], ['query']),
    'adminGetUserPosts' : IDL.Func([IDL.Principal], [IDL.Vec(Post)], ['query']),
    'adminSetSubscriptionStatus' : IDL.Func(
        [IDL.Principal, SubscriptionStatus],
        [],
        [],
      ),
    'adminSuspendUser' : IDL.Func([IDL.Principal], [], []),
    'adminUnsuspendUser' : IDL.Func([IDL.Principal], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkLoginStatus' : IDL.Func(
        [],
        [
          IDL.Variant({
            'existingUser' : IDL.Null,
            'anonymous' : IDL.Null,
            'newUser' : IDL.Null,
          }),
        ],
        ['query'],
      ),
    'createPost' : IDL.Func(
        [EmotionType, IDL.Text, IDL.Opt(Visibility)],
        [Result],
        [],
      ),
    'flagPost' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'generateInviteCode' : IDL.Func([], [IDL.Text], []),
    'getAllRSVPs' : IDL.Func([], [IDL.Vec(RSVP)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCommentsForPost' : IDL.Func([IDL.Text], [IDL.Vec(Comment)], ['query']),
    'getESPStatus' : IDL.Func([], [IDL.Bool], ['query']),
    'getInviteCodes' : IDL.Func([], [IDL.Vec(InviteCode)], ['query']),
    'getMyPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getPublicPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getReactionsForPost' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Reaction)],
        ['query'],
      ),
    'getSeatInfo' : IDL.Func([], [SeatInfo], ['query']),
    'getTextReactionsForPost' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(TextReaction)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'register' : IDL.Func([IDL.Text, Region, IDL.Text], [Result_1], []),
    'revokeInviteCode' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfileUpdate], [], []),
    'submitRSVP' : IDL.Func([IDL.Text, IDL.Bool, IDL.Text], [], []),
    'togglePostVisibility' : IDL.Func([IDL.Text], [Result], []),
    'validateInviteCode' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };