/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface FlagV2 {
    id: string;
    timestamp: Time;
    reporter: Principal;
    reason: FlagReason;
    postId: string;
}
export interface User {
    id: Principal;
    region: Region;
    pseudonym: string;
    createdAt: Time;
    publicPostingCooldownUntil: Time;
    subscriptionStatus: SubscriptionStatus;
    suspended: boolean;
    hasAcknowledgedEntryMessage: boolean;
    hasAcknowledgedPublicPostMessage: boolean;
}
export type FlagReason = {
    __kind__: "Spam";
    Spam: null;
} | {
    __kind__: "Offensive";
    Offensive: null;
} | {
    __kind__: "Harassment";
    Harassment: null;
} | {
    __kind__: "Other";
    Other: string;
};
export interface SeatInfo {
    maxSeats: bigint;
    currentSeats: bigint;
}
export type Result_1 = {
    __kind__: "ok";
    ok: User;
} | {
    __kind__: "err";
    err: RegistrationError;
};
export interface RSVP {
    name: string;
    inviteCode: string;
    timestamp: Time;
    attending: boolean;
}
export interface UserProfileUpdate {
    region: Region;
    pseudonym: string;
}
export type Result = {
    __kind__: "ok";
    ok: Post;
} | {
    __kind__: "err";
    err: string;
};
export interface InviteCode {
    created: Time;
    code: string;
    used: boolean;
}
export type DirectMessageId = string;
export interface Post {
    id: string;
    emotionType: EmotionType;
    content: string;
    createdAt: Time;
    author: Principal;
    updatedAt: Time;
    flaggedForReview: ReviewFlag;
    visibility: Visibility;
}
export interface CommentV2 {
    id: string;
    pseudonym: string;
    commenter: Principal;
    comment: string;
    timestamp: Time;
    postId: string;
}
export interface UserProfile {
    region: Region;
    pseudonym: string;
    subscriptionStatus: SubscriptionStatus;
    suspended: boolean;
    hasAcknowledgedEntryMessage: boolean;
    hasAcknowledgedPublicPostMessage: boolean;
}
export interface DirectMessage {
    id: DirectMessageId;
    to: Principal;
    isCrisisResource: boolean;
    content: string;
    from?: Principal;
    read: boolean;
    timestamp: Time;
}
export enum EmotionType {
    confess = "confess",
    happy = "happy",
    broke = "broke"
}
export enum MessageType {
    resource = "resource",
    admin = "admin"
}
export enum Region {
    India = "India",
    Global = "Global"
}
export enum RegistrationError {
    AnonymousNotAllowed = "AnonymousNotAllowed",
    CapacityReached = "CapacityReached",
    InviteCodeUsed = "InviteCodeUsed",
    AlreadyRegistered = "AlreadyRegistered",
    InvalidInviteCode = "InvalidInviteCode"
}
export enum ReviewFlag {
    none = "none",
    crisisRisk = "crisisRisk"
}
export enum SubscriptionStatus {
    active = "active",
    expired = "expired",
    grace = "grace"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Visibility {
    publicView = "publicView",
    privateView = "privateView"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    acknowledgeEntryMessage(): Promise<void>;
    acknowledgePublicPostMessage(): Promise<void>;
    /**
     * / *** COMMENTS STORE AND FLAG SYSTEM ***
     */
    addComment(postId: string, pseudonym: string, commentText: string): Promise<string>;
    applyPublicPostingCooldown(userId: Principal): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createPost(emotionType: EmotionType, content: string): Promise<Result>;
    deleteComment(commentId: string): Promise<void>;
    flagPost(postId: string, reason: FlagReason): Promise<string>;
    generateInviteCode(): Promise<string>;
    getAllAdminUsers(): Promise<Array<User>>;
    getAllRSVPs(): Promise<Array<RSVP>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getComments(postId: string): Promise<Array<CommentV2>>;
    getDirectMessagesForUser(userId: Principal): Promise<Array<DirectMessage>>;
    getFlags(): Promise<Array<FlagV2>>;
    getInviteCodes(): Promise<Array<InviteCode>>;
    getMyPosts(): Promise<Array<Post>>;
    getPublicPosts(): Promise<Array<Post>>;
    getSeatInfo(): Promise<SeatInfo>;
    getUserProfile(userId: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    markDirectMessageAsRead(messageId: DirectMessageId): Promise<void>;
    permanentlyRemoveUser(userId: Principal): Promise<void>;
    register(pseudonym: string, region: Region, inviteCode: string): Promise<Result_1>;
    removePost(postId: string): Promise<void>;
    revokeInviteCode(_code: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfileUpdate): Promise<void>;
    sendAdminMessage(recipient: Principal, _messageType: MessageType, messageContent: string): Promise<DirectMessageId>;
    sendCrisisResourceMessage(recipient: Principal, _messageType: MessageType): Promise<DirectMessageId>;
    submitRSVP(name: string, attending: boolean, inviteCode: string): Promise<void>;
    suspendUser(userId: Principal): Promise<void>;
    togglePostVisibility(postId: string): Promise<Result>;
    unsuspendUser(userId: Principal): Promise<void>;
    validateInviteCode(code: string): Promise<boolean>;
}
import type { DirectMessage as _DirectMessage, DirectMessageId as _DirectMessageId, EmotionType as _EmotionType, FlagReason as _FlagReason, FlagV2 as _FlagV2, MessageType as _MessageType, Post as _Post, Region as _Region, RegistrationError as _RegistrationError, Result as _Result, Result_1 as _Result_1, ReviewFlag as _ReviewFlag, SubscriptionStatus as _SubscriptionStatus, Time as _Time, User as _User, UserProfile as _UserProfile, UserProfileUpdate as _UserProfileUpdate, UserRole as _UserRole, Visibility as _Visibility } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async acknowledgeEntryMessage(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.acknowledgeEntryMessage();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acknowledgeEntryMessage();
            return result;
        }
    }
    async acknowledgePublicPostMessage(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.acknowledgePublicPostMessage();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acknowledgePublicPostMessage();
            return result;
        }
    }
    async addComment(arg0: string, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addComment(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addComment(arg0, arg1, arg2);
            return result;
        }
    }
    async applyPublicPostingCooldown(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.applyPublicPostingCooldown(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.applyPublicPostingCooldown(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createPost(arg0: EmotionType, arg1: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.createPost(to_candid_EmotionType_n3(this._uploadFile, this._downloadFile, arg0), arg1);
                return from_candid_Result_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPost(to_candid_EmotionType_n3(this._uploadFile, this._downloadFile, arg0), arg1);
            return from_candid_Result_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteComment(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteComment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteComment(arg0);
            return result;
        }
    }
    async flagPost(arg0: string, arg1: FlagReason): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.flagPost(arg0, to_candid_FlagReason_n15(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.flagPost(arg0, to_candid_FlagReason_n15(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async generateInviteCode(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.generateInviteCode();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateInviteCode();
            return result;
        }
    }
    async getAllAdminUsers(): Promise<Array<User>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAdminUsers();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAdminUsers();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllRSVPs(): Promise<Array<RSVP>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRSVPs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRSVPs();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getComments(arg0: string): Promise<Array<CommentV2>> {
        if (this.processError) {
            try {
                const result = await this.actor.getComments(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getComments(arg0);
            return result;
        }
    }
    async getDirectMessagesForUser(arg0: Principal): Promise<Array<DirectMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDirectMessagesForUser(arg0);
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDirectMessagesForUser(arg0);
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFlags(): Promise<Array<FlagV2>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFlags();
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFlags();
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInviteCodes(): Promise<Array<InviteCode>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInviteCodes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInviteCodes();
            return result;
        }
    }
    async getMyPosts(): Promise<Array<Post>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyPosts();
                return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyPosts();
            return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublicPosts(): Promise<Array<Post>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublicPosts();
                return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublicPosts();
            return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSeatInfo(): Promise<SeatInfo> {
        if (this.processError) {
            try {
                const result = await this.actor.getSeatInfo();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSeatInfo();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markDirectMessageAsRead(arg0: DirectMessageId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markDirectMessageAsRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markDirectMessageAsRead(arg0);
            return result;
        }
    }
    async permanentlyRemoveUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.permanentlyRemoveUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.permanentlyRemoveUser(arg0);
            return result;
        }
    }
    async register(arg0: string, arg1: Region, arg2: string): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.register(arg0, to_candid_Region_n39(this._uploadFile, this._downloadFile, arg1), arg2);
                return from_candid_Result_1_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.register(arg0, to_candid_Region_n39(this._uploadFile, this._downloadFile, arg1), arg2);
            return from_candid_Result_1_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async removePost(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removePost(arg0);
            return result;
        }
    }
    async revokeInviteCode(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.revokeInviteCode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.revokeInviteCode(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfileUpdate): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfileUpdate_n45(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfileUpdate_n45(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async sendAdminMessage(arg0: Principal, arg1: MessageType, arg2: string): Promise<DirectMessageId> {
        if (this.processError) {
            try {
                const result = await this.actor.sendAdminMessage(arg0, to_candid_MessageType_n47(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendAdminMessage(arg0, to_candid_MessageType_n47(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async sendCrisisResourceMessage(arg0: Principal, arg1: MessageType): Promise<DirectMessageId> {
        if (this.processError) {
            try {
                const result = await this.actor.sendCrisisResourceMessage(arg0, to_candid_MessageType_n47(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendCrisisResourceMessage(arg0, to_candid_MessageType_n47(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async submitRSVP(arg0: string, arg1: boolean, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitRSVP(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitRSVP(arg0, arg1, arg2);
            return result;
        }
    }
    async suspendUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.suspendUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.suspendUser(arg0);
            return result;
        }
    }
    async togglePostVisibility(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.togglePostVisibility(arg0);
                return from_candid_Result_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.togglePostVisibility(arg0);
            return from_candid_Result_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async unsuspendUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unsuspendUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unsuspendUser(arg0);
            return result;
        }
    }
    async validateInviteCode(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.validateInviteCode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateInviteCode(arg0);
            return result;
        }
    }
}
function from_candid_DirectMessage_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DirectMessage): DirectMessage {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_EmotionType_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EmotionType): EmotionType {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_FlagReason_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FlagReason): FlagReason {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid_FlagV2_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FlagV2): FlagV2 {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_Post_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Post): Post {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_Region_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Region): Region {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_RegistrationError_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RegistrationError): RegistrationError {
    return from_candid_variant_n44(_uploadFile, _downloadFile, value);
}
function from_candid_Result_1_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_1): Result_1 {
    return from_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_ReviewFlag_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReviewFlag): ReviewFlag {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_SubscriptionStatus_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubscriptionStatus): SubscriptionStatus {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_User_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _User): User {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_Visibility_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Visibility): Visibility {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n25(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    region: _Region;
    pseudonym: string;
    createdAt: _Time;
    publicPostingCooldownUntil: _Time;
    subscriptionStatus: _SubscriptionStatus;
    suspended: boolean;
    hasAcknowledgedEntryMessage: boolean;
    hasAcknowledgedPublicPostMessage: boolean;
}): {
    id: Principal;
    region: Region;
    pseudonym: string;
    createdAt: Time;
    publicPostingCooldownUntil: Time;
    subscriptionStatus: SubscriptionStatus;
    suspended: boolean;
    hasAcknowledgedEntryMessage: boolean;
    hasAcknowledgedPublicPostMessage: boolean;
} {
    return {
        id: value.id,
        region: from_candid_Region_n20(_uploadFile, _downloadFile, value.region),
        pseudonym: value.pseudonym,
        createdAt: value.createdAt,
        publicPostingCooldownUntil: value.publicPostingCooldownUntil,
        subscriptionStatus: from_candid_SubscriptionStatus_n22(_uploadFile, _downloadFile, value.subscriptionStatus),
        suspended: value.suspended,
        hasAcknowledgedEntryMessage: value.hasAcknowledgedEntryMessage,
        hasAcknowledgedPublicPostMessage: value.hasAcknowledgedPublicPostMessage
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    region: _Region;
    pseudonym: string;
    subscriptionStatus: _SubscriptionStatus;
    suspended: boolean;
    hasAcknowledgedEntryMessage: boolean;
    hasAcknowledgedPublicPostMessage: boolean;
}): {
    region: Region;
    pseudonym: string;
    subscriptionStatus: SubscriptionStatus;
    suspended: boolean;
    hasAcknowledgedEntryMessage: boolean;
    hasAcknowledgedPublicPostMessage: boolean;
} {
    return {
        region: from_candid_Region_n20(_uploadFile, _downloadFile, value.region),
        pseudonym: value.pseudonym,
        subscriptionStatus: from_candid_SubscriptionStatus_n22(_uploadFile, _downloadFile, value.subscriptionStatus),
        suspended: value.suspended,
        hasAcknowledgedEntryMessage: value.hasAcknowledgedEntryMessage,
        hasAcknowledgedPublicPostMessage: value.hasAcknowledgedPublicPostMessage
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _DirectMessageId;
    to: Principal;
    isCrisisResource: boolean;
    content: string;
    from: [] | [Principal];
    read: boolean;
    timestamp: _Time;
}): {
    id: DirectMessageId;
    to: Principal;
    isCrisisResource: boolean;
    content: string;
    from?: Principal;
    read: boolean;
    timestamp: Time;
} {
    return {
        id: value.id,
        to: value.to,
        isCrisisResource: value.isCrisisResource,
        content: value.content,
        from: record_opt_to_undefined(from_candid_opt_n32(_uploadFile, _downloadFile, value.from)),
        read: value.read,
        timestamp: value.timestamp
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    timestamp: _Time;
    reporter: Principal;
    reason: _FlagReason;
    postId: string;
}): {
    id: string;
    timestamp: Time;
    reporter: Principal;
    reason: FlagReason;
    postId: string;
} {
    return {
        id: value.id,
        timestamp: value.timestamp,
        reporter: value.reporter,
        reason: from_candid_FlagReason_n36(_uploadFile, _downloadFile, value.reason),
        postId: value.postId
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    emotionType: _EmotionType;
    content: string;
    createdAt: _Time;
    author: Principal;
    updatedAt: _Time;
    flaggedForReview: _ReviewFlag;
    visibility: _Visibility;
}): {
    id: string;
    emotionType: EmotionType;
    content: string;
    createdAt: Time;
    author: Principal;
    updatedAt: Time;
    flaggedForReview: ReviewFlag;
    visibility: Visibility;
} {
    return {
        id: value.id,
        emotionType: from_candid_EmotionType_n9(_uploadFile, _downloadFile, value.emotionType),
        content: value.content,
        createdAt: value.createdAt,
        author: value.author,
        updatedAt: value.updatedAt,
        flaggedForReview: from_candid_ReviewFlag_n11(_uploadFile, _downloadFile, value.flaggedForReview),
        visibility: from_candid_Visibility_n13(_uploadFile, _downloadFile, value.visibility)
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    confess: null;
} | {
    happy: null;
} | {
    broke: null;
}): EmotionType {
    return "confess" in value ? EmotionType.confess : "happy" in value ? EmotionType.happy : "broke" in value ? EmotionType.broke : value;
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    none: null;
} | {
    crisisRisk: null;
}): ReviewFlag {
    return "none" in value ? ReviewFlag.none : "crisisRisk" in value ? ReviewFlag.crisisRisk : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    publicView: null;
} | {
    privateView: null;
}): Visibility {
    return "publicView" in value ? Visibility.publicView : "privateView" in value ? Visibility.privateView : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    India: null;
} | {
    Global: null;
}): Region {
    return "India" in value ? Region.India : "Global" in value ? Region.Global : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    expired: null;
} | {
    grace: null;
}): SubscriptionStatus {
    return "active" in value ? SubscriptionStatus.active : "expired" in value ? SubscriptionStatus.expired : "grace" in value ? SubscriptionStatus.grace : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Spam: null;
} | {
    Offensive: null;
} | {
    Harassment: null;
} | {
    Other: string;
}): {
    __kind__: "Spam";
    Spam: null;
} | {
    __kind__: "Offensive";
    Offensive: null;
} | {
    __kind__: "Harassment";
    Harassment: null;
} | {
    __kind__: "Other";
    Other: string;
} {
    return "Spam" in value ? {
        __kind__: "Spam",
        Spam: value.Spam
    } : "Offensive" in value ? {
        __kind__: "Offensive",
        Offensive: value.Offensive
    } : "Harassment" in value ? {
        __kind__: "Harassment",
        Harassment: value.Harassment
    } : "Other" in value ? {
        __kind__: "Other",
        Other: value.Other
    } : value;
}
function from_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _User;
} | {
    err: _RegistrationError;
}): {
    __kind__: "ok";
    ok: User;
} | {
    __kind__: "err";
    err: RegistrationError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_User_n18(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_RegistrationError_n43(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    AnonymousNotAllowed: null;
} | {
    CapacityReached: null;
} | {
    InviteCodeUsed: null;
} | {
    AlreadyRegistered: null;
} | {
    InvalidInviteCode: null;
}): RegistrationError {
    return "AnonymousNotAllowed" in value ? RegistrationError.AnonymousNotAllowed : "CapacityReached" in value ? RegistrationError.CapacityReached : "InviteCodeUsed" in value ? RegistrationError.InviteCodeUsed : "AlreadyRegistered" in value ? RegistrationError.AlreadyRegistered : "InvalidInviteCode" in value ? RegistrationError.InvalidInviteCode : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Post;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Post;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Post_n7(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_User>): Array<User> {
    return value.map((x)=>from_candid_User_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DirectMessage>): Array<DirectMessage> {
    return value.map((x)=>from_candid_DirectMessage_n30(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FlagV2>): Array<FlagV2> {
    return value.map((x)=>from_candid_FlagV2_n34(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Post>): Array<Post> {
    return value.map((x)=>from_candid_Post_n7(_uploadFile, _downloadFile, x));
}
function to_candid_EmotionType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EmotionType): _EmotionType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_FlagReason_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FlagReason): _FlagReason {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_MessageType_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MessageType): _MessageType {
    return to_candid_variant_n48(_uploadFile, _downloadFile, value);
}
function to_candid_Region_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Region): _Region {
    return to_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfileUpdate_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfileUpdate): _UserProfileUpdate {
    return to_candid_record_n46(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    region: Region;
    pseudonym: string;
}): {
    region: _Region;
    pseudonym: string;
} {
    return {
        region: to_candid_Region_n39(_uploadFile, _downloadFile, value.region),
        pseudonym: value.pseudonym
    };
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "Spam";
    Spam: null;
} | {
    __kind__: "Offensive";
    Offensive: null;
} | {
    __kind__: "Harassment";
    Harassment: null;
} | {
    __kind__: "Other";
    Other: string;
}): {
    Spam: null;
} | {
    Offensive: null;
} | {
    Harassment: null;
} | {
    Other: string;
} {
    return value.__kind__ === "Spam" ? {
        Spam: value.Spam
    } : value.__kind__ === "Offensive" ? {
        Offensive: value.Offensive
    } : value.__kind__ === "Harassment" ? {
        Harassment: value.Harassment
    } : value.__kind__ === "Other" ? {
        Other: value.Other
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EmotionType): {
    confess: null;
} | {
    happy: null;
} | {
    broke: null;
} {
    return value == EmotionType.confess ? {
        confess: null
    } : value == EmotionType.happy ? {
        happy: null
    } : value == EmotionType.broke ? {
        broke: null
    } : value;
}
function to_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Region): {
    India: null;
} | {
    Global: null;
} {
    return value == Region.India ? {
        India: null
    } : value == Region.Global ? {
        Global: null
    } : value;
}
function to_candid_variant_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MessageType): {
    resource: null;
} | {
    admin: null;
} {
    return value == MessageType.resource ? {
        resource: null
    } : value == MessageType.admin ? {
        admin: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
